#**Python Basic Terms**

*   Syntax (Valid & Invalid)
*   Comments

In [ ]:
print('This is practice for python')

This is practice for python

In [ ]:
sentence = 'This is practice for python'  #This is sentence
print(sentence)

This is practice for python

# **Python Data Types, Type Casting & Variables**


*   **Text Type:**	str
*   **Numeric Types:**	int, float
*   **Sequence Types:**	list, tuple, range
*   **Mapping Type:**	dict
*   **Set Types:**	set
*   **Boolean Type:**	bool

In [ ]:
name = 'Himanshu'     #string
age = 21              #integer
height = 5.8          #float

profile = ['Himanshu',21,5.8,60,'Engineer']                                     # List Method
profile_2 = ('Madhav',23,5.5,55,'Teacher')                                      # Tuple Method

profile_3 = {'Name':'Himanshu','Role':'Data Analyst','age':21,'City':'Rajkot'}  # Dictionary Method

#In dictionary method there is keys(Name,Role,age,City) and values(Himanshu,Data Analyst,21,Rajkot)
#To know keys we can use   profile_3.keys()
#To know values we can use  profile_3.values()

profile_4 = {'Yogi',55.6,'Teacher', 5.6}                                        # Set Method

In [ ]:
print(profile)
type(profile)       #type is used to know datatype of varaible

['Himanshu', 21, 5.8, 60, 'Engineer']

list

In [ ]:
student1 = ('Rishika', 21, 90.2)    # Tuple --> Cannot modify it
student2 = ['Rishika', 21, 90.2]    # List  --> Can modify it
student3 = {'Rishika', 21, 90.2}    # Set   --> Prints Random Output from given data


print(student1)
print(student2)
print(student3)                     #(SET)Printed Randomly not as per Sqeuence

('Rishika', 21, 90.2)
['Rishika', 21, 90.2]
{90.2, 21, 'Rishika'}

# **Type Casting**

In [ ]:
# prompt: Typecasting in python small example

a = 10
b = str(a)
print(a, type(a))
print(b, type(b))

10 <class 'int'>
10 <class 'str'>

#**Python Operators**

*   Arithmetic operators
*   Assignment operators
*   Comparison operators
*   Logical operators
*   Membership operators

In [ ]:
# Arithmetic Operators (+,-,*,/,%,**)                 # Used with numeric values to perform common mathematical operations

x = 10
y = 5

print(x+y, x-y, x*y, x/y, x%y, x**y)

15 5 50 2.0 0 100000

In [ ]:
# Assignment Operators (=,+=,-=,*=,/=,%=,**=)                # Used to assign values to variables

x, y = 5, 8

# x = y
# x += y       # x = x + y
# x -= y       # x = x - y
# x *= y       # x = x * y
# x /= y       # x = x / y

x += y         # x = x + y  = 5+8 = 13

print(x)

13

In [ ]:
# Comparison Operators (==,!=,<,>,<=,>=)                     # Used to compare two values
# print(x == y, x != y, x < y, x > y, x <= y, x >= y)

x, y = 5, 8

x == y

False

In [ ]:
# Logical Operators (==,!=,<,>,<=,>=)                        # Used to combine conditional statements
# and, or, not
# print(x and y)

case1 =(x < y) or (x == y)
case2 =(x < y) and (x == y)

print(case1)
print(not(case1))
print(case2)

True
False
False

In [ ]:
# Membership Operators (==,!=,<,>,<=,>=)                 # Used to test if a sequence is presented in an object

# print(x in y, x not in y)

x = [1,2,3,4,5]
y = 6

y not in x

True